Issue/183
KasperskyLab/Kaspresso pull request #198
Opened 2020-09-13 14:44 UTC by RuslanMingaliev

Closes #183

2020-09-13 16:21 UTC, matzuk requested changes

2020-09-13 16:21 UTC, matzuk commented on samples/kaspresso-sample/src/androidTest/java/com/kaspersky/kaspressample/docloc_tests/advanced/CustomDirectoryScreenshotSampleTest.kt
> +        }.run {
можно сразу run без пустых before и after

2020-09-13 16:21 UTC, matzuk commented on samples/kaspresso-sample/src/androidTest/java/com/kaspersky/kaspressample/docloc_tests/advanced/CustomDirectoryScreenshotSampleTest.kt
> +
здесь и в других шагах можно без пустых строчек, выглядит избыточно

2020-09-13 16:21 UTC, matzuk commented on samples/kaspresso-sample/src/androidTest/java/com/kaspersky/kaspressample/docloc_tests/advanced/CustomDirectoryScreenshotSampleTest.kt
> +class CustomDirectoryScreenshotSampleTest : DocLocScreenshotTestCase(
Я бы в комменте перед тесто расписал, как скриншоты будут выглядеть по итогу

2020-09-13 16:21 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/testcases/api/testcase/DocLocScreenshotTestCase.kt
> +    private val screenshotDirectoryProvider: ScreenshotDirectoryProvider = DefaultScreenshotDirectoryProvider(groupByRunNumbers = false),
Я бы, наверно, дополнил и вики, расписав, как можно использовать данные филды для распихивания скриншотов

2020-09-13 20:37 UTC, RuslanMingaliev commented on samples/kaspresso-sample/src/androidTest/java/com/kaspersky/kaspressample/docloc_tests/advanced/CustomDirectoryScreenshotSampleTest.kt
> +        }.run {
done

2020-09-13 20:37 UTC, RuslanMingaliev commented on samples/kaspresso-sample/src/androidTest/java/com/kaspersky/kaspressample/docloc_tests/advanced/CustomDirectoryScreenshotSampleTest.kt
> +
done

2020-09-13 20:37 UTC, RuslanMingaliev commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/testcases/api/testcase/DocLocScreenshotTestCase.kt
> +    private val screenshotDirectoryProvider: ScreenshotDirectoryProvider = DefaultScreenshotDirectoryProvider(groupByRunNumbers = false),
done

2020-09-13 20:40 UTC, RuslanMingaliev commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/testcases/api/testcase/DocLocScreenshotTestCase.kt
> +    private val screenshotDirectoryProvider: ScreenshotDirectoryProvider = DefaultScreenshotDirectoryProvider(groupByRunNumbers = false),
как использовать филды решил не расписывать, просто оставил ссылку на сэмпл и описал возможность изменения

2020-09-14 05:58 UTC, matzuk requested changes

2020-09-14 05:58 UTC, matzuk commented on samples/kaspresso-sample/src/androidTest/java/com/kaspersky/kaspressample/docloc_tests/cutomdirectory/FlatDirectoryProvider.kt
> +    override fun getDirectoryForTest(testMethod: TestMethod, runNumber: Int): String = ""
так может здесь показать пример на непустом значении? 
просто более наглядно будет

2020-09-14 05:58 UTC, matzuk commented on samples/kaspresso-sample/src/androidTest/java/com/kaspersky/kaspressample/docloc_tests/cutomdirectory/CustomDirectoryScreenshotSampleTest.kt
> +        }
чуть иное я имел в виду по пустым строкам
между степами - пустая строка
внутри степа (особенно где ты выделяешь Screen.idle и captureScreen) - смысла не вижу

2020-09-14 07:52 UTC, RuslanMingaliev commented on samples/kaspresso-sample/src/androidTest/java/com/kaspersky/kaspressample/docloc_tests/cutomdirectory/FlatDirectoryProvider.kt
> +    override fun getDirectoryForTest(testMethod: TestMethod, runNumber: Int): String = ""
Issue создавалась для того, чтобы показать, как избавиться от избыточной вложенности внутри директории со скриншотами. В том числе в чате ни один раз спрашивали, как её убрать. Пустая строка здесь показательный пример того, как это сделать.

2020-09-14 08:43 UTC, RuslanMingaliev commented on samples/kaspresso-sample/src/androidTest/java/com/kaspersky/kaspressample/docloc_tests/cutomdirectory/CustomDirectoryScreenshotSampleTest.kt
> +        }
done

2020-09-14 09:44 UTC, matzuk approved these changes

2020-09-14 10:35 UTC, merged