Kaspresso allure support
KasperskyLab/Kaspresso pull request #255
Opened 2021-06-03 12:56 UTC by eakurnikov

2021-06-04 06:19 UTC, matzuk requested changes

2021-06-04 06:19 UTC, matzuk commented on allure_support/build.gradle.kts
> +import Dependencies.Versions
У нас в названиях модулей нет нижнего подчеркивания, только тире. Давай здесь также сделаем.

2021-06-04 06:19 UTC, matzuk commented on allure_support/src/main/kotlin/com/kaspersky/components/allure_support/runner/KaspressoTestRunner.kt
> +        Log.d("KASPRESSO", "Creating KaspressoTestRunner")
Мне не очень нравится, что мы сюда тупо андроидовский логгер суем. Нужно подумать, как просунуть наши интерфейсы логгеров.

2021-06-04 06:19 UTC, matzuk commented on allure_support/src/main/kotlin/com/kaspersky/components/allure_support/runner/KaspressoTestRunner.kt
> +        Log.d("KASPRESSO", "Creating KaspressoTestRunner")
KASPRESSO - в константы

2021-06-04 06:19 UTC, matzuk commented on allure_support/src/main/kotlin/com/kaspersky/components/allure_support/runner/KaspressoTestRunner.kt
> +    ): CharSequence = getCharSequence("listener").withListeners(*addListeners)
"listener" - в константы?

2021-06-04 06:19 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/logcat/dumper/LogcatDumper.kt
> +interface LogcatDumper {
Кстати нужно подумать, относим ли мы `LogcatDumper` к `device` пакету или нет? Если да, то по идее `LogcatDumper` должен быть доступен с класса `Device`.

2021-06-04 07:08 UTC, eakurnikov commented on allure_support/src/main/kotlin/com/kaspersky/components/allure_support/runner/KaspressoTestRunner.kt
> +        Log.d("KASPRESSO", "Creating KaspressoTestRunner")
Ну реализовать разве что интерфейс тут еще раз) Каспрессо тут еще нет. Ну либ логгер он же все равно андроидовский юзает. Еще вариант не писать тут ничего просто и все)

2021-06-04 07:08 UTC, eakurnikov commented on allure_support/src/main/kotlin/com/kaspersky/components/allure_support/runner/KaspressoTestRunner.kt
> +        Log.d("KASPRESSO", "Creating KaspressoTestRunner")
Да зачем, интернирование же есть. Мы что, тег прям будем менять когда-нибудь?)

2021-06-04 07:09 UTC, eakurnikov commented on allure_support/src/main/kotlin/com/kaspersky/components/allure_support/runner/KaspressoTestRunner.kt
> +    ): CharSequence = getCharSequence("listener").withListeners(*addListeners)
Эта строка тем более 1 раз используется

2021-06-04 07:12 UTC, eakurnikov commented on allure_support/src/main/kotlin/com/kaspersky/components/allure_support/runner/KaspressoTestRunner.kt
> +                grantPermission(targetContext.packageName, WRITE_EXT_STORAGE_PERMISSION)
Пермишены тут выдаются хостовому приложению, но мне кажется для CI пофиг, все равно на тестовых девайсах и эмулях это все

2021-06-04 07:21 UTC, matzuk requested changes

2021-06-04 07:21 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/screenshots/screenshotmaker/ExternalScreenshotMaker.kt
> +        ).takeScreenshot(file, 1.0f, params.quality)
1.0f - может тоже в константу?

2021-06-04 07:21 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/video/videorecorder/VideoRecorderImpl.kt
> +        if (videoRecordingThread == null) {
мб исключение таки бросать? Ибо ноль и info log - очень слабые помощники в поисках причины отсутствия видео =)

2021-06-04 07:21 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/video/videorecorder/VideoRecorderImpl.kt
> +    private var videoRecordingThread: VideoRecordingThread? = null
Я вот в прошлом ревью отмечал, а это норм, что мы прям голый поток вот так юзаем? Может через Executors? Или нам нужно четко прикончить поток в какой-то момент времени, а Executors этого вроде не дают сделать?

2021-06-04 07:21 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/viewhierarchy/ViewHierarchyDumper.kt
> +interface ViewHierarchyDumper {
Такой же вопрос, что и про `LogcatDumper`

2021-06-04 07:21 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/viewhierarchy/ViewHierarchyDumperImpl.kt
> +            UiDevice.getInstance(InstrumentationRegistry.getInstrumentation()).dumpWindowHierarchy(logcatFile)
А почему мы кстати не пробрасываем UiDevice через конструктор?
Есть еще другие места, где я такое видел.

2021-06-04 07:21 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/docloc/DocLocScreenshotCapturer.kt
> +            val screenshotFile = resourceFilesProvider.provideScreenshotFile(screenshotName, "fails")
"fails" - в константы

2021-06-04 07:21 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/files/DirsProvider.kt
> +///storage/emulated/0/video/run_1/com.kaspersky.kaspressample.simple_tests.SimpleTest/test/Video_SimpleTest.mp4
?

2021-06-04 07:21 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/files/DirsProvider.kt
> +package com.kaspersky.kaspresso.files
Мы же вроде везде разделяем интерфейс и имплементацию по разным файлам

2021-06-04 07:21 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/files/DirsProvider.kt
> +            InstrumentationRegistry.getInstrumentation().targetContext.applicationContext.getDir(
и кстати контексты мы же тоже можем через конструктор тащить, у нас же есть в `Kaspresso` и `context`, и `targetContext`

2021-06-04 07:21 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/interceptors/watcher/testcase/impl/logging/DumpLogcatInterceptor.kt
> +        logcatDumper.dump("TestLogcat")
Откуда это "TestLogcat"?

2021-06-04 07:21 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/interceptors/watcher/testcase/impl/logging/DumpLogcatInterceptor.kt
> -class BuildStepReportWatcherInterceptor(
Публичный API не поломаем?

2021-06-04 07:21 UTC, matzuk commented on samples/kaspresso-allure-support-sample/src/androidTest/java/com/kaspersky/kaspresso_allure_support_sample/AllureSupportTest.kt
> +class AllureSupportTest : TestCase(withAllureSupport()) {
Не хватает какого-то ридми, типа а что мы получаем то в конце, и как это использовать?

2021-06-04 07:25 UTC, eakurnikov commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/logcat/dumper/LogcatDumperImpl.kt
> +import com.kaspersky.kaspresso.kaspresso.Kaspresso.Companion.DEFAULT_LIB_LOGGER_TAG
А что смущает?

2021-06-04 07:30 UTC, eakurnikov commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/screenshots/screenshotmaker/ExternalScreenshotMaker.kt
> +        ).takeScreenshot(file, 1.0f, params.quality)
Я хотел в парам положить, но в реализации не увидел его использования) Этот примитив интернируется и вообще используется 1 раз, зачем лишнее поле?

2021-06-04 07:37 UTC, eakurnikov commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/files/DirsProvider.kt
> +///storage/emulated/0/video/run_1/com.kaspersky.kaspressample.simple_tests.SimpleTest/test/Video_SimpleTest.mp4
упс

2021-06-04 07:38 UTC, eakurnikov commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/interceptors/watcher/testcase/impl/logging/DumpLogcatInterceptor.kt
> +        logcatDumper.dump("TestLogcat")
Ну интерсептор сам решает, как файлик назвать)

2021-06-04 07:40 UTC, eakurnikov commented on samples/kaspresso-allure-support-sample/src/androidTest/java/com/kaspersky/kaspresso_allure_support_sample/AllureSupportTest.kt
> +class AllureSupportTest : TestCase(withAllureSupport()) {
Ну каспрессо билдер это, который аллюр интерсепторы в каспрессо сетит. Получаем все ресурсы в аллюровской папке. Если собрать отчет из этого всего, все файлы будут в отчете.

2021-06-04 07:47 UTC, eakurnikov commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/video/videorecorder/VideoRecorderImpl.kt
> +    private var videoRecordingThread: VideoRecordingThread? = null
Ну можно single thread executor, ему callable передать и держать ссылку на future, а потом ее канселить. Callable только придется свой реализовать, чтобы был метод killRecordingProcess. Но это вроде просто второй способ сделать то же самое, какие у тебя опасения по поводу треда?

2021-06-04 08:36 UTC, eakurnikov commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/video/videorecorder/VideoRecorderImpl.kt
> +    private var videoRecordingThread: VideoRecordingThread? = null
А не, даже свой Future нужно создавать с методом killRecordingProcess, и переопределять метод submit у ExecutorService, чтобы он нашу Future возвращал, а не стандартную. Можно сделать, но мне непонятно, зачем оно надо.

2021-06-04 08:37 UTC, eakurnikov commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/video/videorecorder/VideoRecorderImpl.kt
> +        if (videoRecordingThread == null) {
Да, тут можно IllegalStateException бросать

2021-06-04 08:39 UTC, eakurnikov commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/logcat/dumper/LogcatDumper.kt
> +interface LogcatDumper {
Положил по смыслу фичи просто рядом.

2021-06-07 04:50 UTC, matzuk commented on allure_support/src/main/kotlin/com/kaspersky/components/allure_support/runner/KaspressoTestRunner.kt
> +        Log.d("KASPRESSO", "Creating KaspressoTestRunner")
Причем тут интернирование =) 
Это просто лучшие практики выносить все строчки и цифры в осмысленные константы.

2021-06-07 04:57 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/logcat/dumper/LogcatDumperImpl.kt
> +import com.kaspersky.kaspresso.kaspresso.Kaspresso.Companion.DEFAULT_LIB_LOGGER_TAG
ну мы нигде эти константы не юзаем в явном виде
я бы через конструктор бросал

2021-06-07 04:58 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/logcat/dumper/LogcatDumper.kt
> +interface LogcatDumper {
@RuslanMingaliev а ты что думаешь?

2021-06-07 05:00 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/screenshots/screenshotmaker/ExternalScreenshotMaker.kt
> +        ).takeScreenshot(file, 1.0f, params.quality)
Ну потому что со стороны это кажется какой-то непонятной константой. 
А вот если бы было что-то вроде `.takeScreenshot(file, ORIGINAL_SCALE, params.quality)`, то уже по-другому читается)

2021-06-07 05:06 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/video/videorecorder/VideoRecorderImpl.kt
> +    private var videoRecordingThread: VideoRecordingThread? = null
У меня желание сделать только проще и безопаснее. Когда речь идет о чистых потоках, то мне сразу же вспоминаются приколы с InterruptedExceptions и тд. Но тут вроде никакой синхронизации и внешних прерываний быть не должно.
Кстати, а если тест вдруг умер, то кто и как убьет этот поток? Мб нужна стартовая проверка и выставление таймаута какого-то?

2021-06-07 05:09 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/video/videorecorder/VideoRecorderImpl.kt
> +        val thread: VideoRecordingThread = videoRecordingThread!!
а зачем здесь отдельная переменная, и тебя не смущает `!!`?

2021-06-07 05:09 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/video/videorecorder/VideoRecorderImpl.kt
> +class VideoRecorderImpl(
мб я бы отметил явно, шо тут однопоточно все должно быть

2021-06-07 05:09 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/interceptors/watcher/testcase/impl/logging/DumpLogcatInterceptor.kt
> +        logcatDumper.dump("TestLogcat")
Ага, понял, тогда давай название тоже утащим в константы

2021-06-07 05:10 UTC, matzuk commented on samples/kaspresso-allure-support-sample/src/androidTest/java/com/kaspersky/kaspresso_allure_support_sample/AllureSupportTest.kt
> +class AllureSupportTest : TestCase(withAllureSupport()) {
а ты пробовал собирать кстати?

2021-06-07 05:36 UTC, matzuk requested changes

2021-06-07 05:36 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/internal/wait/Wait.kt
> +internal fun <T> wait(
Вообще есть более правильный и гибкий `FlakySafetyAlgorithm`

2021-06-07 05:36 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/kaspresso/Kaspresso.kt
> +                    stepWatcherInterceptors.add(
а к `advanced` разве нужно относить? мб к AllureBuilder более логично?

2021-06-07 05:36 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/kaspresso/Kaspresso.kt
> +        lateinit var screenshotParams: ScreenshotParams
мб в AllureBuilder все должно уходить?

2021-06-07 13:05 UTC, RuslanMingaliev commented on allure_support/src/main/kotlin/com/kaspersky/components/allure_support/runner/KaspressoTestRunner.kt
> +                grantPermission(targetContext.packageName, WRITE_EXT_STORAGE_PERMISSION)
А это будет работать на Android 11+ со scoped storage?

2021-06-07 13:08 UTC, RuslanMingaliev commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/video/videorecorder/VideoRecorderImpl.kt
> +        val thread: VideoRecordingThread = videoRecordingThread!!
лучше делать с `checkNotNull` — с ним, насколько я помню, и смарт касты работают и более осмысленная ошибка, если значение null

2021-06-07 16:23 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/video/videorecorder/VideoRecorderImpl.kt
> +        val thread: VideoRecordingThread = videoRecordingThread!!
тоже вариант, согласен

2021-08-17 10:45 UTC, RuslanMingaliev commented
@eakurnikov перенес изменения сюда: #265

2021-08-17 10:45 UTC, closed without merging