Allure interceptors cleanup
KasperskyLab/Kaspresso pull request #265
Opened 2021-07-04 16:29 UTC by RuslanMingaliev

2021-07-13 07:06 UTC, matzuk requested changes

2021-07-13 07:06 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/files/resources/impl/DefaultResourcesRootDirsProvider.kt
> +class DefaultResourcesRootDirsProvider : ResourcesRootDirsProvider {
1. Я в итоге не до конца понял, где именно в итоге все хранится
2. Мне кажется, что проставление рутов должно быть прям в `Kaspresso` файле, чтобы легко можно было обнаружить все конфигурации.

2021-07-13 07:06 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/internal/extensions/other/ThrowableExt.kt
> -internal fun Throwable.getStackTraceAsString(): String =
а почему убираем?

2021-07-13 07:06 UTC, matzuk commented on samples/kaspresso-sample/src/androidTest/kotlin/com/kaspersky/kaspressample/docloc_tests/cutomdirectory/CustomDirectoryScreenshotSampleTest.kt
> -    screenshotsDirectory = File("custom_directory"),
эм, это же пример про запись скриншотов в кастомную директорию
тест же теперь не будет работать как надо

2021-07-13 07:12 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/kaspresso/Kaspresso.kt
> +                    stepWatcherInterceptors.add(
неплохо бы, конечно, в доке обозначить, что дают эти интерсепторы и где это смотреть

2021-08-01 21:41 UTC, RuslanMingaliev commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/logcat/dumper/LogcatDumperImpl.kt
> +                tags = listOf(DEFAULT_LIB_LOGGER_TAG, DEFAULT_TEST_LOGGER_TAG)
Посмотрел, как логи используются. Там такая цепочка
`LogcatDumperImpl#dumpLogcat -> LogcatImpl#dumpLogcat -> LogcatImpl#prepareCommand`

в `prepareCommand` параметр `logs` никак не используется. WTF? 
Кроме того, надо будет избавиться от nullable параметров и использовать пустой сет по умолчанию.

2021-08-01 21:41 UTC, RuslanMingaliev commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/logcat/dumper/LogcatDumperImpl.kt
> +                tags = listOf(DEFAULT_LIB_LOGGER_TAG, DEFAULT_TEST_LOGGER_TAG)
Вынес в параметры конструктора

2021-08-01 21:42 UTC, RuslanMingaliev commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/video/recorder/VideoRecorder.kt
> +    fun stop(): File?
Не знаю, лучше у @eakurnikov уточнить по поводу реализации
Добавил коммент пока, но мне не нравится nullable, не знаю пока как сделать лучше

2021-08-01 21:45 UTC, RuslanMingaliev commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/video/recorder/VideoRecorderImpl.kt
> +class VideoRecorderImpl(
Не очень понимаю, что ты имеешь в виду. Запись видео может быть многопоточной? :)

2021-08-01 21:45 UTC, RuslanMingaliev commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/screenshots/Screenshots.kt
> +    fun takeAndApply(tag: String, block: File.() -> Unit)
\+

2021-08-01 21:49 UTC, RuslanMingaliev commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/video/recorder/VideoRecorderImpl.kt
> +    private fun <T> wait(
Не получилось заюзать из коробки, пока оставил так. Функция приватная, юзается только в этом конкретном месте

2021-08-01 21:50 UTC, RuslanMingaliev commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/viewhierarchy/ViewHierarchyDumperImpl.kt
> +            UiDevice.getInstance(InstrumentationRegistry.getInstrumentation()).dumpWindowHierarchy(logcatFile)
Скопировал из соседнего PR. Поправил так, как ты говоришь, согласен с комментарием.

2021-08-01 21:52 UTC, RuslanMingaliev commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/viewhierarchy/ViewHierarchyDumper.kt
> +interface ViewHierarchyDumper {
Согласен, что неочевидно. Сохраняется в глобальный дефолтный файл провайдер. Подумаю, как можно сделать лучше. Возможно, не в рамках этого PR, ок?

2021-08-01 21:53 UTC, RuslanMingaliev commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/failure/FailureLoggingProviderImpl.kt
> +        logger.e(Log.getStackTraceString(error))
Насколько я понял, @eakurnikov просто заюзал уже имеющийся метод, который делает то же самое. А наш удалил. В принципе, я не против того, чтобы убрать дублирование

2021-08-01 21:56 UTC, RuslanMingaliev commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/files/DefaultDirsProvider.kt
> +            InstrumentationRegistry.getInstrumentation().targetContext.applicationContext.getDir(
Да. Но очень неудобно передавать его из мест, где создаются инстансы :(

2021-08-01 21:56 UTC, RuslanMingaliev commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/files/DefaultDirsProvider.kt
> +            Environment.getExternalStorageDirectory().resolve(path)
ответил выше

2021-08-01 21:56 UTC, RuslanMingaliev commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/files/resources/ResourcesDirsProvider.kt
> +    fun onNewTestRun()
Согласен, тут абстракции потекли. Подумаю, как сделать лучше

2021-08-01 21:57 UTC, RuslanMingaliev commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/files/resources/impl/DefaultResourcesRootDirsProvider.kt
> +class DefaultResourcesRootDirsProvider : ResourcesRootDirsProvider {
Согласен, подумаю, как сделать лучше

2021-08-01 21:57 UTC, RuslanMingaliev commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/internal/extensions/other/ThrowableExt.kt
> -internal fun Throwable.getStackTraceAsString(): String =
используем такой же метод из Log везде

2021-08-01 21:57 UTC, RuslanMingaliev commented on samples/kaspresso-sample/src/androidTest/kotlin/com/kaspersky/kaspressample/docloc_tests/cutomdirectory/CustomDirectoryScreenshotSampleTest.kt
> -    screenshotsDirectory = File("custom_directory"),
Кек, да. Поправлю

2021-08-01 21:58 UTC, RuslanMingaliev commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/kaspresso/Kaspresso.kt
> +                    stepWatcherInterceptors.add(
Напишу отдельную доку

2021-08-01 22:01 UTC, RuslanMingaliev commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/logcat/dumper/LogcatDumper.kt
> +interface LogcatDumper {
\+

2021-08-03 16:43 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/video/recorder/VideoRecorder.kt
> +    fun stop(): File?
Думаю, должно быть что-то типичное типа `Result<Success, Error>`

2021-08-03 16:44 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/video/recorder/VideoRecorderImpl.kt
> +class VideoRecorderImpl(
Я про то, что если у данного класса метод `start` дернется почти одновременно с разных потоков

2021-08-03 16:46 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/video/recorder/VideoRecorderImpl.kt
> +    private fun <T> wait(
а че там не получилось?
короче, точно не хочется дублирования и вот этого всего

2021-08-03 16:47 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/viewhierarchy/ViewHierarchyDumper.kt
> +interface ViewHierarchyDumper {
Ну давай подумаем. Хотя бы тогда написать в комменте к интерфейсу подробно

2021-08-03 16:48 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/files/DefaultDirsProvider.kt
> +            InstrumentationRegistry.getInstrumentation().targetContext.applicationContext.getDir(
Ну..такое, короче =)

2021-09-25 11:36 UTC, eakurnikov commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/video/recorder/VideoRecorderImpl.kt
> +    private fun <T> wait(
@RuslanMingaliev погоди, а зачем ее сюда тащить, она же у меня из com.kaspersky.kaspresso.internal.wait дерагется, ты ее просто перетащил сюда или шо?

2021-09-25 11:38 UTC, eakurnikov commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/failure/FailureLoggingProviderImpl.kt
> +                logger.e(Log.getStackTraceString(error))
Тут e должно быть аргументом, мы итерируемся по вложенным в error эксепшенам и пишем их трейсы

2021-09-28 10:13 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/video/recorder/VideoRecorderImpl.kt
> +class VideoRecorderImpl(
Но такого тут быть не может особо

2021-09-28 10:32 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/files/resources/impl/DefaultResourcesRootDirsProvider.kt
> +class DefaultResourcesRootDirsProvider : ResourcesRootDirsProvider {
Посмотрел еще раз. Да, в целом, все более-менее очевидно. Оставим так.

2021-09-30 10:54 UTC, matzuk commented
Done in #273

2021-09-30 10:54 UTC, closed without merging