Kaspresso allure support v2
KasperskyLab/Kaspresso pull request #272
Opened 2021-09-25 17:49 UTC by eakurnikov

TODO:
1) Нужно чистить логкат перед/после каждого теста. В последнем коммите сделал это, но это флакает почему-то.
2) Не дублировать скрины в семплах.

2021-09-26 19:50 UTC, RuslanMingaliev commented on Makefile
> +publish_release:
это же в мастере уже?

2021-09-26 19:50 UTC, RuslanMingaliev commented on README.md
> +1. If the `mavenCentral` repository does not exist, include it to your root `build.gradle` file:
это же в мастере уже?

2021-09-26 19:50 UTC, RuslanMingaliev commented on allure-support/gradle.properties
> +publish.artifactGroup=com.kaspersky.android-components
ненужный файл, бинтрей уже неактуален

2021-09-26 20:24 UTC, eakurnikov commented on Makefile
> +publish_release:
Да, я мастер пульнул

2021-09-26 20:24 UTC, eakurnikov commented on README.md
> +1. If the `mavenCentral` repository does not exist, include it to your root `build.gradle` file:
Да, я мастер пульнул

2021-09-26 20:25 UTC, eakurnikov commented on allure-support/gradle.properties
> +publish.artifactGroup=com.kaspersky.android-components
А, по инерции правил, уберу. Ну тогда во всех модулях надо убрать

2021-09-27 08:06 UTC, RuslanMingaliev commented on allure-support/gradle.properties
> +publish.artifactGroup=com.kaspersky.android-components
Хм, ты прав. Я был уверен, что удалял уже эти файлы

2021-09-28 11:08 UTC, matzuk requested changes

2021-09-28 11:08 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/kaspresso/Kaspresso.kt
> +        lateinit var screenshotParams: ScreenshotParams
где комментарии, как к другим полям?

2021-09-28 13:36 UTC, eakurnikov commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/internal/wait/Wait.kt
> +internal fun <T> wait(
Так мне не надо флеки сефели, мне подождать надо) Там можно заморочиться и синхронизировать их как-то, но флеки сефели совсем тут н при чем

2021-09-28 13:44 UTC, eakurnikov commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/video/recorder/VideoRecorder.kt
> +    fun stop(): File?
Ну я не против, можно упороться, но здесь нет потока этих данных, и стейтов не 3, там либо вернулся файл, либо нет, так что это чисто косметика. Нул возможно стоит в месте вызова метода stop обрабатывать для наглядности, но фактически внутри рекордера и так в лог пишется, если нул возвращается.

2021-09-28 13:45 UTC, eakurnikov commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/video/recorder/VideoRecorderImpl.kt
> +    override fun stop(): File? {
А что здесь по-котлиновски?) Двойная проверка на нул?)

2021-09-28 13:53 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/video/recorder/VideoRecorderImpl.kt
> +    override fun stop(): File? {
нет хотя бы `!!`

2021-09-28 14:00 UTC, eakurnikov commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/video/recorder/VideoRecorderImpl.kt
> +    override fun stop(): File? {
`
override fun stop(): File? =
        videoRecordingThread
            ?.let { thread ->
                thread.killRecordingProcess()
                doAfterRecordingStopped {
                    thread.interrupt()
                    videoRecordingThread = null
                }
                thread.file
            }
            ?: run {
                logger.i("Can't stop video recording as it was not started")
                null
            }
`

2021-09-28 14:05 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/internal/wait/Wait.kt
> +internal fun <T> wait(
мм, я понял
ну хорошо, давай так и оставим

2021-09-28 14:10 UTC, eakurnikov commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/kaspresso/Kaspresso.kt
> +        lateinit var screenshotParams: ScreenshotParams
Ну там такие комментарии, конечно, не очень содержательные) Добавлю аналогичные

2021-09-28 14:10 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/video/recorder/VideoRecorderImpl.kt
> +    override fun stop(): File? {
Лучше уж так
```kotlin
    override fun stop(): File? {
        val thread: VideoRecordingThread = videoRecordingThread ?: run {
            logger.i("Can't stop video recording as it was not started")
            return null
        }

        logger.i("Stopping video recording")
        thread.killRecordingProcess()
        doAfterRecordingStopped {
            thread.interrupt()
            videoRecordingThread = null
        }
        return thread.file
    }

```

2021-09-28 14:28 UTC, eakurnikov commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/testcases/api/testcase/DocLocScreenshotTestCase.kt
>  abstract class DocLocScreenshotTestCase(
Можно старый задепрекейтить и добавить новый класс, но тогда старые провайдеры придется в коде держать.

2021-09-29 04:01 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/video/recorder/VideoRecorder.kt
> +    fun stop(): File?
В целом, наверху в комментах написано про null. Давайте пока оставим как есть.

2021-09-29 04:02 UTC, matzuk commented on kaspresso/src/main/kotlin/com/kaspersky/kaspresso/kaspresso/Kaspresso.kt
> +        lateinit var screenshotParams: ScreenshotParams
я согласен, но тут чисто для единообразия

2021-09-30 06:22 UTC, matzuk approved these changes

2021-09-30 10:53 UTC, merged