Issue 283/replace deprecated activity test rule with ActivityScenarioTestRule
KasperskyLab/Kaspresso pull request #365
Opened 2022-06-19 20:44 UTC by sergio-sastre

2022-06-20 14:40 UTC, RuslanMingaliev submitted a review, later dismissed
LGTM

2022-06-22 14:05 UTC, matzuk approved these changes

2022-06-28 09:44 UTC, Nikitae57 commented on samples/kaspresso-sample/src/androidTest/kotlin/com/kaspersky/kaspressample/compose_tests/WebComposeTest.kt
> +                                containsText("Ask questiop")
nit: "questiop"?

2022-06-28 10:11 UTC, Nikitae57 commented on samples/kaspresso-sample/src/androidTest/kotlin/com/kaspersky/kaspressample/docloc_tests/advanced/ProductDocLocScreenshotTestCase.kt
> -open class ProductDocLocScreenshotTestCase : DocLocScreenshotTestCase(locales = "en,ru") {
It's still mentioned in 07_DocLoc.md

2022-06-28 13:44 UTC, Nikitae57 requested changes
As a couple of types were removed, we need to update docs. nit: readme and *.md files under wiki folder still contain code with ActivityScenarioTestRule

2022-07-14 19:45 UTC, sergio-sastre commented
> As a couple of types were removed, we need to update docs. nit: readme and *.md files under wiki folder still contain code with ActivityScenarioTestRule

Thanks for the hint!
I made the corresponding changes

2022-07-20 08:18 UTC, eakurnikov approved these changes

2022-08-04 14:07 UTC, sergio-sastre commented
> > As a couple of types were removed, we need to update docs. nit: readme and *.md files under wiki folder still contain code with ActivityScenarioTestRule
> 
> Thanks for the hint! I made the corresponding changes

@Nikitae57 Could you review again, please?

2022-08-06 13:32 UTC, matzuk commented
Hey @sergio-sastre!
Could you merge the latest master? We updated/fixed our examples.
@AzamatCherchesov please review too and merge the PR if everything is good.

2022-08-08 08:19 UTC, Nikitae57 commented
@sergio-sastre could you resolve conflicts and make sure that tests are green, please?

2022-08-09 06:18 UTC, sergio-sastre commented
> Hey @sergio-sastre!
> Could you merge the latest master? We updated/fixed our examples.
> @AzamatCherchesov please review too and merge the PR if everything is good.

@AzamatCherchesov Done :)

2022-08-10 11:06 UTC, AzamatCherchesov approved these changes

2022-08-10 11:10 UTC, Nikitae57 approved these changes

2022-08-10 11:11 UTC, merged