Third party report code conventions
KasperskyLab/Kaspresso pull request #373
Opened 2022-07-13 10:30 UTC by maxsurovtsev

В этом ПРе создается модуль с конвеншнами для сборки third-party-code отчетов.
Сами конвеншны пустые и ссылка на репозиторий хранится в пропертях из-за политики безопасности в Лаборатории Касперского. 
Генерируем мы эти отчеты в контуре ЛК следующим образом:
* Заполняем проперти ссылкой на внутренний репозиторий с зависимостями
* Применяем патч, который прописывает необходимые зависимости в third-party-report/build.gradle и заполняет конвеншны логикой
* Запускаем таску по сбору отчета

2022-07-13 10:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KasperskyLab/Kaspresso?pullRequest=373) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KasperskyLab/Kaspresso?pullRequest=373) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KasperskyLab/Kaspresso?pullRequest=373) it.</sub>

2022-07-13 11:13 UTC, AzamatCherchesov submitted a review, later dismissed

2022-07-13 11:36 UTC, RuslanMingaliev requested changes

2022-07-13 11:36 UTC, RuslanMingaliev commented on allure-support/build.gradle.kts
> +    id("convention.third-party-report")
Почем только к нескольким модулям применен плагин? У нас публикуется гораздо больше артефактов

2022-07-13 11:36 UTC, RuslanMingaliev commented on build-logic/settings.gradle.kts
> +    val kasperskyRepoUrl: String? by settings
Это какой-то секрет? Откуда он будет тянуться при публикации?

2022-07-13 11:36 UTC, RuslanMingaliev commented on build-logic/third-party-report/build.gradle.kts
> +plugins {
Почему это convention плагин? Не вижу никакой настройки

2022-07-13 11:36 UTC, RuslanMingaliev commented on build-logic/third-party-report/src/main/kotlin/convention.air.gradle.kts
> +// Please do not remove this file. This file is used for new releases.
Не понимаю, для чего вообще этот PR :) 
Добавь, пожалуйста, контекста к описанию PR в формате "Какую проблему решал - Что сделал - Что дальше"

2022-07-13 11:42 UTC, maxsurovtsev commented on allure-support/build.gradle.kts
> +    id("convention.third-party-report")
Пока что плагин умеет работать только с android-модулями. Как только появится поддержка java/kotlin модулей, добавлю и туда

2022-07-13 11:52 UTC, maxsurovtsev commented on build-logic/third-party-report/src/main/kotlin/convention.air.gradle.kts
> +// Please do not remove this file. This file is used for new releases.
Обновил описание

2022-07-13 11:55 UTC, maxsurovtsev commented on build-logic/third-party-report/build.gradle.kts
> +plugins {
Вот тут как раз прописываются зависимости, нужные для конвеншна
Этот файл вместе с convention.air.gradle.kts и convention.third-party-report.gradle.kts оставлены пустыми, чтобы проект продолжал собираться.

2022-07-13 11:58 UTC, AzamatCherchesov commented on build-logic/settings.gradle.kts
> +    val kasperskyRepoUrl: String? by settings
@RuslanMingaliev для релиза мы будем скачивать с локальных ресурсов патч, накатывать его и отправлять отчеты для получения апрува на релиз

2022-07-20 08:28 UTC, eakurnikov commented
Guys I think we should use English as it is a an international open-source :) We have non-russian speaking contributors.

2022-08-06 13:29 UTC, matzuk commented
@RuslanMingaliev hey!
Has Maxim resolved all issues that bothered you? WDYT?

2022-09-22 16:56 UTC, merged