Issue 541 custom kakao click support
KasperskyLab/Kaspresso pull request #546
Opened 2023-07-25 07:47 UTC by matzuk

2023-07-25 09:34 UTC, Nikitae57 requested changes

2023-07-25 09:34 UTC, Nikitae57 commented on docs/Wiki/Kaspresso_configuration.en.md
> +Kaspresso provides the possibility to override custom Espresso clicks by custom clicks.
Override custom clicks by custom clicks... Maybe just "override espresso custom clicks"?

2023-07-25 09:34 UTC, Nikitae57 commented on docs/Wiki/Kaspresso_configuration.en.md
> +Kakao library provides a set of prepared custom clicks which improves the stability of tests especially on devices under the high load.
Suggest "the" before "tests" and "devices", and "a" before "high load"

2023-07-25 09:34 UTC, Nikitae57 commented on docs/Wiki/Kaspresso_configuration.ru.md
> +Kaspresso предоставляет возможность переопределить стандартные клики Espresso.
Maybe "Кастомные клики"  to align with an English doc

2023-07-25 09:34 UTC, Nikitae57 commented on docs/Wiki/Kaspresso_configuration.ru.md
> +Пример, как заиспользовать кастомные клики в вашем тесте представлено в [ClickTest](../../samples/kaspresso-sample/src/androidTest/kotlin/com/kaspersky/kaspressample/click_tests/ClickTest.kt).
"," after "тесте", "предоставлен" (without o on the end)

2023-07-25 09:34 UTC, Nikitae57 commented on samples/kaspresso-sample/src/androidTest/kotlin/com/kaspersky/kaspressample/click_tests/ClickTest.kt
> +class ClickTest : TestCase(
Suggest "CustomClickTest". We have plenty of clicks in the other tests

2023-07-25 11:14 UTC, AzamatCherchesov commented
Some problems with detekt, @matzuk have a look pls

2023-07-27 12:27 UTC, Nikitae57 approved these changes

2023-07-27 19:22 UTC, AzamatCherchesov approved these changes

2023-07-28 05:26 UTC, merged